# Generated by Django 5.1.3 on 2024-11-30 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_admin_user_alter_employee_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_name', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer_type', models.CharField(choices=[('employee', 'Employee'), ('employer', 'Employer'), ('anonymous', 'Anonymous')], default='anonymous', max_length=10)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_reviews', to='accounts.employee')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_reviews', to='accounts.employer')),
            ],
        ),
    ]
