# Generated by Django 5.1.3 on 2024-11-28 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('hard', 'Hard'), ('soft', 'Soft')], default='hard', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(choices=[('location', 'Location'), ('hybrid', 'Hybrid'), ('distance', 'Distance')], default='location', max_length=10)),
                ('week_day', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('contract_type', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.contracttype')),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.employer')),
                ('function', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.function')),
                ('language', models.ManyToManyField(to='vacancies.language')),
                ('question', models.ManyToManyField(to='vacancies.question')),
                ('skill', models.ManyToManyField(to='vacancies.skill')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
                ('vacancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy')),
            ],
        ),
    ]
