# Generated by Django 5.1.3 on 2024-11-29 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_admin_user_alter_employee_user_and_more'),
        ('vacancies', '0002_vacancy_latitude_vacancy_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyvacancy',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='applyvacancy',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='contract_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.contracttype'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employer'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.function'),
        ),
    ]
